<?php
/**
 * Base default configuration.
 * DO NOT EDIT THIS FILE!
 *
 * @author Dmitriy Lunin
 */
class CfgBase
{
    /** Имя сервера БД */
    public const DB_HOSTNAME = 'localhost';

    /** Номер порта для подключения к БД. Оставьте пустым для стандартного. */
    public const DB_PORT = null;

    /** Имя пользователя БД */
    public const DB_USERNAME = '';

    /** Пароль к БД */
    public const DB_PASSWORD = '';

    /** Имя БД */
    public const DB_BASENAME = '';

    /** Префикс таблиц в БД */
    public const DB_TBL_PREFIX = '';

    /** Кодировка БД */
    public const DB_CHARSET = 'utf8';

    /** Кешировать SELECT'ы (альтернатива кеша СУБД) */
    public const SQL_CACHE_IS_ON = false;

    /** Полный путь к файлу, в к-рый логировать запросы-не-select'ы */
    public const SQL_LOG_TO_FILE = '';

    /** Логировать запросы-не-select'ы (со стек-трейсами) в БД. Требуется ведение истории. */
    public const SQL_LOG_TO_DB = false;

    /* ### */

    /**
     * Закрытый и открытый ключи RSA (2048 bit).
     *
     * Пример генерации пары ключей:
     * $ openssl genrsa -out rsa.pem 2048 && cat rsa.pem
     * $ openssl rsa -in rsa.pem -pubout && rm rsa.pem
     */
    public const RSA_PRIVATE_KEY = '';

    public const RSA_PUBLIC_KEY = '';

    /* ### */

    /** Режим отладки */
    public const DEBUG_IS_ON = false;

    /** Записывать информацию о JS-ошибках на стороне клиента */
    public const JS_ERRORS_LOGGING_IS_ON = true;

    /** Обнаружение попыток взлома */
    public const GUARD_IS_ON = true;

    /** Список доверенных IP. Маски и диапазоны не поддерживаются. Разделитель - ; */
    public const GUARD_WHITE_LIST = '';

    /** На сайте надо вести историю */
    public const HISTORY_IS_ON = false;

    /** Использовать сжатие JS- и CSS-файлов */
    public const MINIFY_IS_ON = false;

    /** Путь к контроллеру Minify */
    public const MINIFY_PATH = '/min/?f=';

    /** Сообщать посетителям сайта об использовании неподдерживаемой версии браузера */
    public const BROWSER_CHECKING_IS_ON = false;

    /* ### */

    /** Определение мобильной версии сайта */
    public const MOBILE_VERSION_IS_ON = true;

    /** Префикс хоста мобильной версии сайта */
    public const MOBILE_DOMAIN_PREFIX = 'm.';

    /**
     * Уровень основного домена сайта.
     * Используется для формирования альтернативных URL для мобильных устройств.
     *
     * domain.com -> 2
     * subdomain.domain.com -> 3
     * ...
     */
    public const MAIN_DOMAIN_LEVEL = 2;

    /* ### */

    /**
     * Параметры отправки email'ов.
     */
    public const MAILER = 'mail'; // 'mail' | 'sendmail' | 'smtp'

    /** Параметры SMTP */
    public const MAILER_SMTP_HOST = '';
    // What kind of encryption to use on the SMTP connection:
    // - 'ssl' == SMTP with implicit TLS, a.k.a. RFC8314 SMTPS
    // - 'tls' == SMTP+STARTTLS
    public const MAILER_SMTP_ENCRYPTION = 'tls';
    // SMTP port number:
    // - 465 for SMTPS
    // - 587 for SMTP+STARTTLS
    public const MAILER_SMTP_PORT = 587;
    public const MAILER_SMTP_AUTH = true;
    public const MAILER_SMTP_USER = '';
    public const MAILER_SMTP_PASSWORD = '';

    /* ### */

    /** На сайте допускается удаление учётных записей */
    public const USER_DELETION_IS_ON = true;

    /** Группы учётных записей */
    public const GRP_GUEST      = 'guest';      // Гость
    public const GRP_ADMINS     = 'admin';      // Администратор
    public const GRP_DEVELS     = 'developer';  // Разработчик
    public const GRP_REGISTERED = 'registered'; // Зарегистрированный пользователь

    /* ### */

    /** Distributed configuration file in Apache */
    public const HTACCESS_FILE_NAME  = '.htaccess';
    public const HTACCESS_FILE_CHMOD = 0444;

    /* ### */

    /** Имена различных служебных директорий */
    public const DS              = DIRECTORY_SEPARATOR;
    // {$PATH}/app/
    public const DIR_CMF_ROOT    = __DIR__ . self::DS . '..' . self::DS;
    // {$PATH}/app/..
    public const DIRS_ROOT       = self::DIR_CMF_ROOT . '..';
    // {$PATH}/app/../
    public const DIR_ROOT        = self::DIRS_ROOT . self::DS;
    // {$PATH}/app/controllers/
    public const DIR_CONTROLLERS = self::DIR_CMF_ROOT . 'controllers' . self::DS;
    // {$PATH}/app/functions/
    public const DIR_FUNCTIONS   = self::DIR_CMF_ROOT . 'functions' . self::DS;
    // {$PATH}/app/model/
    public const DIR_MODEL       = self::DIR_CMF_ROOT . 'model' . self::DS;
    // {$PATH}/app/model_maps/
    public const DIR_MODEL_MAPS  = self::DIR_CMF_ROOT . 'model_maps' . self::DS;
    // {$PATH}/app/view/
    public const DIR_VIEW        = self::DIR_CMF_ROOT . 'view' . self::DS;
    // {$PATH}/app/resource_maps/
    public const DIR_RES_MAPS    = self::DIR_CMF_ROOT . 'resource_maps' . self::DS;

    // имя директории в корне сайта, в которой будут храниться служебные и загружаемые файлы
    public const DIR_FILES_NAME  = 'files';
    // {$PATH}/files/
    public const DIR_FILES       = self::DIR_ROOT . self::DIR_FILES_NAME . self::DS;
    // {$PATH}/files/tmp/
    public const DIR_TMP_FILES   = self::DIR_FILES . 'tmp' . self::DS;
    // {$PATH}/log/
    public const DIR_LOG         = self::DIR_ROOT . 'log' . self::DS;
    // {$PATH}/log/failed_notices/
    public const DIR_LOG_NOTICES = self::DIR_LOG . 'failed_notices' . self::DS;
    // {$PATH}/modules/
    public const DIR_MODULES     = self::DIR_ROOT . 'modules' . self::DS;
    // имя дочерней директории, в которой будут создаваться миниатюры изображений
    public const DIR_THUMBS_NAME = '_thumbs';
    // _thumbs/
    public const DIR_THUMBS      = self::DIR_THUMBS_NAME . self::DS;

    // URL директории статичных ресурсов
    public const STATIC_RESOURCES_URL_PREFIX  = '/static/';
    public const STATIC_MODULES_URL_PREFIX  = '/modules/';

    /* ### */

    /** Директории шаблонов Smarty */
    public const SMARTY_TEMPLATE_DIR = [
        'account'     => self::DIR_VIEW . 'account' . self::DS . 'tpl',
        'admin'       => self::DIR_VIEW . 'admin' . self::DS . 'tpl',
        'entity_edit' => self::DIR_VIEW . 'entity_edit' . self::DS . 'tpl',
        'mail'        => self::DIR_VIEW . 'mail',
        'main'        => self::DIR_VIEW . 'main' . self::DS . 'tpl',
        'menu'        => self::DIR_VIEW . 'menu' . self::DS . 'tpl',
        'special'     => self::DIR_VIEW . 'special' . self::DS . 'tpl'
    ];

    /** Расширение файлов шаблонов Smarty */
    public const SMARTY_TEMPLATE_EXT = '.tpl';

    /** Директория для хранения скомпилированных шаблонов Smarty */
    public const SMARTY_COMPILE_DIR = self::DIR_CMF_ROOT . 'cache';

    /** Директория для кеша шаблонов Smarty */
    public const SMARTY_CACHE_DIR = self::SMARTY_COMPILE_DIR;

    /** Директория плагинов Smarty */
    public const SMARTY_PLUGINS_DIR = self::DIR_MODEL . 'utils' . self::DS . 'Smarty';

    /** Левый разделитель, используемый в языке шаблонов Smarty */
    public const SMARTY_LEFT_DELIMITER = '{';

    /** Правый разделитель, используемый в языке шаблонов Smarty */
    public const SMARTY_RIGHT_DELIMITER = '}';

    /* ### */

    /** Кодировка внутреннего представления текстовых данных */
    public const CHARSET = 'UTF-8';

    /** Права доступа к директориям и файлам по умолчанию */
    public const CHMOD_FOLDERS = 0775;
    public const CHMOD_FILES   = 0664;

    /* ### */

    /** ID страницы "/" */
    public const PAGE_ID_FRONT = 1;

    /** URL главной страницы "админки" */
    public const URL_ADMIN_PANEL = '/admin-panel/';

    /** URL страницы редактирования [Сущностей] */
    public const URL_ENTITY_EDIT = self::URL_ADMIN_PANEL . 'entity_edit/';

    /** URL страницы 403 */
    public const URL_403 = '/access_denied/';

    /** URL страницы 404 */
    public const URL_404 = '/page_not_found/';

    /** URL страницы "История" */
    public const URL_HISTORY = '/history/';

    /** URL страницы аутентификации */
    public const URL_ACCOUNT_LOGIN = '/login-user/';
    public const URL_ACCOUNT_LOGIN_ADMIN = '/login-admin/';

    /** URL страницы завершения сессии */
    public const URL_ACCOUNT_LOGOUT = '/?action=logout';

    /** URL страницы регистрации аккаунта */
    public const URL_ACCOUNT_SIGNUP = '/account/signup/';

    /** URL страницы редактирования аккаунта */
    public const URL_ACCOUNT_EDIT = '/account/edit/';

    /** URL страницы восстановления пароля аккаунта */
    public const URL_ACCOUNT_RESET_PASSWORD = '/account/lost-password/';

    /**
     * URL страницы, на которую будет перенаправлен
     * пользователь после аутентификации.
     */
    public const URL_AFTER_LOGIN = '/account/';

    /**
     * URL страницы, на которую будет перенаправлен
     * пользователь после завершения сессии.
     */
    public const URL_AFTER_LOGOUT = '/';

    /* ### */

    /**
     * Шаблон страниц, считающийся безопасным по причине того,
     * что на нём не добавляется пользовательский код
     */
    public const SAFE_TEMPLATE = 'admin';

    /* ### */

    /** Используемая тема EasyUI */
    public const UI_EASYUI_THEME = 'gray';

    /** Размер кнопок в формах. Допустимые значения: xl, m, s. */
    public const UI_BUTTONS_SIZE = 'm';

    /** Цвета кнопок. Допустимые значения: white, red, blue */
    // обычные кнопки
    public const UI_BUTTONS_COLOR = 'white';
    // кнопки SUBMIT
    public const UI_BUTTONS_SUBMIT_COLOR = 'blue';
    // кнопки DELETE
    public const UI_BUTTONS_DELETE_COLOR = 'red';

    /** Ширина создаваемых миниатюр изображений */
    public const UI_THUMBS_WIDTH = 186;

    /** Высота создаваемых миниатюр изображений */
    public const UI_THUMBS_HEIGHT = 136;

    /* ### */

    /** Префикс имени полей формы, которые при разборе нужно игнорировать */
    public const DEFAULT_EMPTY_PREFIX = '__vis_';

    /** Значение поля в форме, которое считается пустым */
    public const DEFAULT_EMPTY_VALUE = '___EMPTY';

    /** Ограничение количества записей на странице по умолчанию */
    public const DEFAULT_RECORDS_LIMIT = 30;
}
