<?php
// карта базовых классов CMF AEngine
return [
    'Application'                   => 'core/Application',
    'Cookies'                       => 'core/Cookies',
    'DBCommand'                     => 'core/DBCommand',
    'DBQueryBuilder'                => 'core/DBQueryBuilder',
    'Extender'                      => 'core/Extender',
    'Guard'                         => 'core/Guard',
    'Logger'                        => 'core/Logger',
        'Psr\\Log\\LogLevel'            => 'core/Logger/LogLevel',
        'Logger\\LogToInterface'        => 'core/Logger/LogToInterface',
        'Logger\\AbstractLoggerHandler' => 'core/Logger/AbstractLoggerHandler',
        'Logger\\LogToFile'             => 'core/Logger/LogToFile',
        'Logger\\LogToHtml'             => 'core/Logger/LogToHtml',
        'Logger\\LogToFirePHP'          => 'core/Logger/LogToFirePHP',
        'Logger\\LogToChromePHP'        => 'core/Logger/LogToChromePHP',
    'Module'                        => 'core/Module',
    'Properties'                    => 'core/Properties',
    'Request'                       => 'core/Request',
    'Response'                      => 'core/Response',
	'RTP'                           => 'core/RTP',
    'Security'                      => 'core/Security',
    'Session'                       => 'core/Session',
    'SiteOptions'                   => 'core/SiteOptions',
    'StaticResourceImporter'        => 'core/StaticResourceImporter',
    'User'                          => 'core/User',

    'Ajax'         => 'utils/Ajax',
    'Benchmarker'  => 'utils/Benchmarker',
    'DBDump'       => 'utils/DBDump',
    'Dictionary'   => 'utils/Dictionary',
    'EasyUILoader' => 'utils/EasyUILoader',
    'FsArchive'    => 'utils/FsArchive',
    'FsDirectory'  => 'utils/FsDirectory',
    'FsFile'       => 'utils/FsFile',
    'FsImage'      => 'utils/FsImage',
    'Html'         => 'utils/Html',
    'MenuBuilder'  => 'utils/MenuBuilder',
    'Notifier'     => 'utils/Notifier',
    'Randomizer'   => 'utils/Randomizer',
    'RobotsTxt'    => 'utils/RobotsTxt',
    'Sitemap'      => 'utils/Sitemap',
    'Time'         => 'utils/Time',
    'Tokenizer'    => 'utils/Tokenizer',

    'Action'             => 'helpers/Action',
    'FetchBy'            => 'helpers/FetchBy',
    'FetchOptions'       => 'helpers/FetchOptions',
    'FieldInfo'          => 'helpers/FieldInfo',
    'FieldInfoIterator'  => 'helpers/FieldInfoIterator',
    'ObjectOptions'      => 'helpers/ObjectOptions',

    'AbstractEntityMeta'     => 'entities_base/AbstractEntityMeta',
    'AbstractEntity'         => 'entities_base/AbstractEntity',
    'RelationshipsMetaTrait' => 'entities_base/RelationshipsMetaTrait',
    'RelationshipsTrait'     => 'entities_base/RelationshipsTrait',
    'StatusesMetaTrait'      => 'entities_base/StatusesMetaTrait',
    'StatusesTrait'          => 'entities_base/StatusesTrait',
    'UniqueFieldsMetaTrait'  => 'entities_base/UniqueFieldsMetaTrait',
    'UniqueFieldsTrait'      => 'entities_base/UniqueFieldsTrait',

    'CBlockMeta'     => 'entities/CBlockMeta',
    'CBlock'         => 'entities/CBlock',
    'CHistoryMeta'   => 'entities/CHistoryMeta',
    'CHistory'       => 'entities/CHistory',
    'CPageMeta'      => 'entities/CPageMeta',
    'CPage'          => 'entities/CPage',
    'CTextBlockMeta' => 'entities/CTextBlockMeta',
    'CTextBlock'     => 'entities/CTextBlock',
    'CUserMeta'      => 'entities/CUserMeta',
    'CUser'          => 'entities/CUser',

    'EntityManager'              => 'services_base/EntityManager',
    'EntityManagerInterface'     => 'services_base/EntityManagerInterface',
    'EntityRender'               => 'services_base/EntityRender',
    'PositProcessorTrait'        => 'services_base/PositProcessorTrait',
    'RelationshipsManagerTrait'  => 'services_base/RelationshipsManagerTrait',
    'UniqueFieldsProcessorTrait' => 'services_base/UniqueFieldsProcessorTrait',

    'BlockManager'     => 'services/BlockManager',
    'HistoryManager'   => 'services/HistoryManager',
    'PageManager'      => 'services/PageManager',
    'TextBlockManager' => 'services/TextBlockManager',
    'UserManager'      => 'services/UserManager',

    'AccessDeniedEx'           => 'exceptions/AccessDeniedEx',
    'DBCommandEx'              => 'exceptions/DBCommandEx',
    'EntityEditEx'             => 'exceptions/EntityEditEx',
    'EntityNotFoundEx'         => 'exceptions/EntityNotFoundEx',
    'FeatureNotAvailableEx'    => 'exceptions/FeatureNotAvailableEx',
    'FilesUploadEx'            => 'exceptions/FilesUploadEx',
    'FilesystemEx'             => 'exceptions/FilesystemEx',
    'InternalEx'               => 'exceptions/InternalEx',
    'InvalidFileEx'            => 'exceptions/InvalidFileEx',
    'JSONEx'                   => 'exceptions/JSONEx',
    'MailEx'                   => 'exceptions/MailEx',
    'PageEditEx'               => 'exceptions/PageEditEx',
    'RequiredFieldIsEmptyEx'   => 'exceptions/RequiredFieldIsEmptyEx',
    'SecurImageEx'             => 'exceptions/SecurImageEx',
    'SenseiExceptionInterface' => 'exceptions/SenseiExceptionInterface',
    'TokenizerEx'              => 'exceptions/TokenizerEx',
    'UserEx'                   => 'exceptions/UserEx',
    'UserAuthenticationEx'     => 'exceptions/UserAuthenticationEx',
    'UserPasswordEx'           => 'exceptions/UserPasswordEx',
    'UserRegistrationEx'       => 'exceptions/UserRegistrationEx',

    'BlockNotFoundEx'          => 'exceptions/BlockNotFoundEx',
    'TextBlockNotFoundEx'      => 'exceptions/TextBlockNotFoundEx',
    'UserNotFoundEx'           => 'exceptions/UserNotFoundEx',
];
